CREATE DATABASE IF NOT EXISTS jdbc_demo;
USE jdbc_demo;

CREATE TABLE IF NOT EXISTS personnes  (
Id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
nom VARCHAR(50) NOT NULL,
prenom VARCHAR(50) NOT NULL
);

